from sqlalchemy import text

from alembic import op
import sqlalchemy as sa
from app.models.user import UserType, UserGender

# revision identifiers, used by Alembic.
revision = '01796e80fda3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),

        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),

        sa.Column('user_type', sa.Enum(UserType, name="user_type", create_type=False), nullable=False),
        sa.Column('gender', sa.Enum(UserGender, name="user_gender", create_type=False), nullable=False),

        sa.Column('country_id', sa.BigInteger(), nullable=False),
        sa.Column("language_id", sa.BigInteger(), nullable=False),

        sa.Column('birth_date', sa.DATE(), nullable=False),

        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),

        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),

        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    pass
