from sqlalchemy import text

from alembic import op
import sqlalchemy as sa
from app.models.user import UserType, UserGender

# revision identifiers, used by Alembic.
revision = '01796e80fda3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),

        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),

        sa.Column('user_type', sa.Enum(UserType, name="user_type", create_type=False), nullable=False),
        sa.Column('gender', sa.Enum(UserGender, name="user_gender", create_type=False), nullable=False),

        sa.Column('country_id', sa.BigInteger(), nullable=False),
        sa.Column("language_id", sa.BigInteger(), nullable=False),

        sa.Column('birth_date', sa.DATE(), nullable=False),

        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),

        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),

        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("index_user_phone"), "user", ["phone"], unique=True)
    op.create_index(op.f("index_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("index_user_first_name"), "user", ["first_name"])
    op.create_index(op.f("index_user_last_name"), "user", ["last_name"])
    op.create_index(op.f("index_user_user_type"), "user", ["user_type"])
    op.create_index(op.f("index_user_gender"), "user", ["gender"])
    op.create_index(op.f("index_user_country_id"), "user", ["country_id"])
    op.create_index(op.f("index_user_language_id"), "user", ["language_id"])
    op.create_index(op.f("index_user_birth_date"), "user", ["birth_date"])
    op.create_index(op.f("index_user_password"), "user", ["password"])
    op.create_index(op.f("index_user_created_at"), "user", ["created_at"])
    op.create_index(op.f("index_user_deleted_at"), "user", ["deleted_at"])


def downgrade():
    op.drop_index("index_user_phone", table_name="user")
    op.drop_index("index_user_email", table_name="user")
    op.drop_index("index_user_first_name", table_name="user")
    op.drop_index("index_user_last_name", table_name="user")
    op.drop_index("index_user_user_type", table_name="user")
    op.drop_index("index_user_gender", table_name="user")
    op.drop_index("index_user_country_id", table_name="user")
    op.drop_index("index_user_language_id", table_name="user")
    op.drop_index("index_user_birth_date", table_name="user")
    op.drop_index("index_user_password", table_name="user")
    op.drop_index("index_user_created_at", table_name="user")
    op.drop_index("index_user_deleted_at", table_name="user")
    op.drop_table("user")
